# Generated by Django 3.0.7 on 2020-06-19 14:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_attempt_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='input_time_logs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=1024),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='content',
            field=models.CharField(max_length=1024),
        ),
    ]
