# Generated by Django 3.0.7 on 2020-06-19 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0004_reduce_content_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastestAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.PositiveIntegerField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Attempt')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise')),
            ],
            options={
                'ordering': ('time_spent',),
            },
        ),
        migrations.AddConstraint(
            model_name='fastestattempt',
            constraint=models.UniqueConstraint(fields=('creator', 'exercise'), name='unique_fastest_attempt'),
        ),
    ]
