# Generated by Django 3.0.7 on 2020-06-21 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0005_fastest_attempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(choices=[('enUSAQ', 'en_US.Am.QWERTY'), ('enUSAD', 'en_US.Am.Dvorak'), ('enUSAC', 'en_US.Am.Colemak'), ('ukUAAЙ', 'uk_UA.Am.ЙЦУКЕН'), ('ruRUAЙ', 'ru_RU.Am.ЙЦУКЕН')], max_length=6)),
                ('attempt_counter', models.PositiveIntegerField(default=0)),
                ('input_counter', models.PositiveIntegerField(default=0)),
                ('mistake_counter', models.PositiveIntegerField(default=0)),
                ('delay_counter', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'layout'),
            },
        ),
        migrations.AddConstraint(
            model_name='layoutstatistics',
            constraint=models.UniqueConstraint(fields=('user', 'layout'), name='unique_layout_statistics'),
        ),
    ]
